Code Changes
LincolnVR/vrc-headpat-counter pull request #5
Opened 2022-12-27 18:13 UTC by suzedash

- added vrmaifest file to run with steamvr
- option to change ip and port in config
- print and log options in config

2022-12-27 18:13 UTC, suzedash commented
updated files are in 
https://github.com/suzedash/vrc-headpat-counter/releases/tag/v1.0.2

2022-12-30 03:09 UTC, LincolnVR commented on osc_counter/oscserver.py
> -                self.messenger.has_new_content(tracker := self.filemanager.get_tracker())):
Both the indentation you have done here and the one I previously had are valid and shown in the PEP8 style guide.

As personal preference I would like to maintain having the additional indentation as it helps me quickly differentiate between the long if statement and the rest of the code block.

2022-12-30 03:20 UTC, LincolnVR requested changes
Just one change on the indentation on the if statement. 
Is this PR supposed to have an exe attached to it? I see that you changed the instructions on the documentation to run an exe, but I am not seeing it attached to this PR? 

Other than that I really love these additions and changes. Thanks for implementing version control as well.

2022-12-30 04:00 UTC, suzedash commented
[VRCHeadpatCounter.zip](https://github.com/LincolnVR/vrc-headpat-counter/files/10323016/VRCHeadpatCounter.zip)

2022-12-30 04:06 UTC, LincolnVR approved these changes
Looks great! love the additions and added quality of life this brings

2022-12-30 04:06 UTC, merged